### ISSUE TITLE
Feature 1: User can select a category and difficulty

### ISSUE THREAD

**Issue by Kitlonglai** [Kitlonglai/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Select a category of different trivia questions to answer.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Creates a home page for the trivia app, and allows users to choose a category of questions from a drop down menu.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-08-07 at 7 06 21 PM](https://github.com/Kitlonglai/ajax-project/assets/111219005/540b67de-496b-4a9d-b4e6-480237deec41)
![Screenshot 2023-08-07 at 7 07 18 PM](https://github.com/Kitlonglai/ajax-project/assets/111219005/9397961a-5fd8-4a63-8d71-cef02ed677db)
![Screenshot 2023-08-07 at 7 55 21 PM](https://github.com/Kitlonglai/ajax-project/assets/111219005/2b37e813-2902-456c-812a-f5685672e40b)
![Screenshot 2023-08-07 at 7 55 48 PM](https://github.com/Kitlonglai/ajax-project/assets/111219005/fbc6cd8d-b22b-4477-9fb4-114c0cc9191c)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make a header and body in HTML that matches the wire frame.
- [x] Create a drop down menu to select different options
- [x] Each option should be a different category of questions.
- [x] Make a category for all categories, film & tv, sports, geography, history, animals, celebrities.
- [x] Each category should have its own unique api url associated with it, by using template literals in the url object
- [x] Create a radio button that allows users to select a difficulty
- [x] Use fetch to retrieve each category of questions
- [x] The fetch function should have a response and data returned
- [x] The response should be tested and a user is required to enter both a category and difficulty
- [x] The response should match the difficulty and category selected on the menu
- [x] Each start over or play again button should return user back to this starting page
- [x] Ensure that each click of a category advances the user to the next page, to choose a difficulty level
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
