### ISSUE TITLE
Feature 2: User can choose a difficulty of trivia questions asked

### ISSUE THREAD

**Issue by Kitlonglai** [Kitlonglai/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can choose a difficulty of their chosen category of questions, ranging from easy, medium, or hard.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-08-07 at 7 55 21 PM](https://github.com/Kitlonglai/ajax-project/assets/111219005/f22cba6a-4f46-491b-aa25-e71e015f90d3)
![Screenshot 2023-08-07 at 7 55 48 PM](https://github.com/Kitlonglai/ajax-project/assets/111219005/46381636-121f-47f8-be47-6297a4dc383a)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [ ] Create a new page loads after user selects a category
- [ ] Create a header and body text that matches the wireframe
- [ ] Create 3 buttons for 3 different difficulty levels
- [ ] The 3 difficulty button levels should say easy, medium, and hard
- [ ] Each difficulty button should be stylized with green (easy), yellow (medium), and red (hard)
- [ ] Each difficulty button should link to a different api url representing each level of difficulty
- [ ]  Use fetch to retrieve each difficulty of questions
- [ ] The fetch function should have a response and data returned
- [ ] There should be a start over button on the bottom of the page which returns user to the starting page of categories
- [ ] Ensure that each click of a difficulty advances the user to the next page, to begin the actual quiz questions
- [ ] - **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
