### ISSUE TITLE
Feature 2: User can answer multiple choice trivia questions

### ISSUE THREAD

**Issue by Kitlonglai** [Kitlonglai/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view 10 multiple choice questions each with 4 different answers. User can answer the correct answer which increases their score. Right or wrong answers will advance the user to the next question.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-08-07 at 8 28 27 PM](https://github.com/Kitlonglai/ajax-project/assets/111219005/fdd76f41-0e19-4f98-95f9-b356c40f3c7c)
![Screenshot 2023-08-07 at 8 29 49 PM](https://github.com/Kitlonglai/ajax-project/assets/111219005/98622ef9-efef-4bc0-b1c1-1c4cf274bc31)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] Create a new page that loads after user selects a difficulty level
- [x] This new page should have a header and a body in html
- [ ] The page should load question 1 of the quiz in the body
- [ ] The page should have 4 buttons 
- [ ] There should be an array that is accessed from the api call
- [ ] Each button should show 1 of 4 different answers to the question, linked from the array of answers
- [ ] There should only be one correct answer, the rest should be false (unless it is a question that asks to select all those that apply)
- [ ] When a correct answer is clicked, the button will have an event listener with a callback function that changes the color of the button to green and displays the word "correct"
- [ ] When an incorrect answer is clicked, the button will have an event listener with a callback function that changes the color of the button to red and displays the word "incorrect"
- [ ] Any click of a button should advance the user to the next question
- [ ] There should be a function to record a players score. 
- [ ] Any correct answer will increment the score by one.
- [ ] There should be a start over button for each trivia quiz question that returns user to the starting page for categories
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
