### ISSUE TITLE
Feature 3: User can receive a grade for how correct answers

### ISSUE THREAD

**Issue by Kitlonglai** [Kitlonglai/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After answering all 10 quiz questions, they will receive a score out of 10, with a point rewarded for each question they answered correctly.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-08-07 at 9 03 09 PM](https://github.com/Kitlonglai/ajax-project/assets/111219005/e8d23a7a-d7db-4a3d-8713-7068cb1b3dc5)
![Screenshot 2023-08-07 at 9 03 51 PM](https://github.com/Kitlonglai/ajax-project/assets/111219005/3283d237-a3e2-4191-a8d3-da5bde3effdd)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] The final grade page should load after user answers the 10th question
- [ ] Create a header and highlight body text for answers correct /10 in html
- [ ] For the body text, use the function that contains the object storing the score, that was incremented by 1 for each correct score
- [ ] Display the score, ensuring the function is actually incrementing by 1 for each correct answer
- [ ] Add a play again button below the score that sends the user back to the starting page
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
